version: 0.2
phases:
  install: 
    runtime-versions:
      docker: 18
    commands: 
      - apt-get update -y
      - apt-get install -y jq
      - apt-get install update
      - curl -L https://npmjs.org/install.sh | sudo sh
      - npm -v
  build:
    commands:
      -  bash deploy.sh us-east-1 $stackName
      - echo "teste" >> elb.txt
  post_build:
    commands:
      - echo "DONE!!!!"
    
artifacts:
  files: 
    - elb.txt